from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand

from catalog.models import Vehicle
from dossiers.models import Dossier, DossierStatusHistory, Option


class Command(BaseCommand):
    help = "Seed simple de données de test"

    def handle(self, *args, **options):
        User = get_user_model()

        user, _ = User.objects.get_or_create(
            username="admin",
            defaults={
                "email": "admin@example.com",
                "is_staff": True,
                "is_superuser": True,
            },
        )

        options_data = [
            {
                "code": "insurance_all_risk",
                "name": "Assurance tous risques",
                "description": "Couverture assurance complète du véhicule",
                "is_active": True,
                "is_default_in_lld": True,
                "monthly_price": 0,
            },
            {
                "code": "roadside_assistance",
                "name": "Assistance dépannage",
                "description": "Assistance en cas de panne ou incident",
                "is_active": True,
                "is_default_in_lld": True,
                "monthly_price": 0,
            },
            {
                "code": "maintenance_sav",
                "name": "Entretien et SAV",
                "description": "Entretien courant et service après-vente",
                "is_active": True,
                "is_default_in_lld": True,
                "monthly_price": 0,
            },
            {
                "code": "technical_control",
                "name": "Contrôle technique",
                "description": "Prise en charge du contrôle technique",
                "is_active": True,
                "is_default_in_lld": True,
                "monthly_price": 0,
            },
        ]

        created_options = []
        for option_data in options_data:
            option, _ = Option.objects.update_or_create(
                code=option_data["code"],
                defaults=option_data,
            )
            created_options.append(option)

        vehicles_data = [
            {
                "reference": "MM_REN_001",
                "brand": "Renault",
                "model": "Clea",
                "trim": "Zen",
                "category": "Citadine",
                "image": "img/catalog_cars/renault_bleue1.PNG",
                "year": 2020,
                "mileage": 45000,
                "fuel_type": Vehicle.FuelType.DIESEL,
                "gearbox": Vehicle.GearboxType.MANUAL,
                "color": "Bleu métallisé",
                "doors": 5,
                "seats": 5,
                "fiscal_power": 5,
                "power_hp": 95,
                "co2_emissions": 108,
                "consumption": 4.6,
                "crit_air": "Crit’Air 2",
                "warranty": "12 mois",
                "included_options": "Bluetooth, Régulateur de vitesse, Climatisation, Aide au démarrage en côte, Radar de recul",
                "price_sale": 12900.00,
                "price_monthly": 129.00,
                "description": "Citadine moderne et économique, idéale pour les trajets urbains et les déplacements quotidiens. Elle offre une conduite souple, une consommation maîtrisée et des équipements pratiques comme le Bluetooth et le régulateur de vitesse.",
                "offer_type": Vehicle.OfferType.BOTH,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
            {
                "reference": "MM_REN_002",
                "brand": "Renault",
                "model": "Captor",
                "trim": "Intens",
                "category": "SUV",
                "image": "img/catalog_cars/renault_orange1.PNG",
                "year": 2019,
                "mileage": 52000,
                "fuel_type": Vehicle.FuelType.GASOLINE,
                "gearbox": Vehicle.GearboxType.AUTOMATIC,
                "color": "Orange métallisé",
                "doors": 5,
                "seats": 5,
                "fiscal_power": 6,
                "power_hp": 130,
                "co2_emissions": 124,
                "consumption": 5.8,
                "crit_air": "Crit’Air 1",
                "warranty": "12 mois",
                "included_options": "GPS, Caméra de recul, Climatisation automatique, Bluetooth, Régulateur de vitesse, Jantes alliage",
                "price_sale": 15400.00,
                "price_monthly": 139.00,
                "description": "SUV compact polyvalent, parfait pour la ville comme pour les sorties en famille. Son habitacle spacieux, sa position de conduite surélevée et ses aides au stationnement en font un véhicule agréable au quotidien.",
                "offer_type": Vehicle.OfferType.SALE,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
            {
                "reference": "MM_REN_003",
                "brand": "Renault",
                "model": "Megan",
                "trim": "Business",
                "category": "Berline",
                "image": "img/catalog_cars/renault_gris1.PNG",
                "year": 2020,
                "mileage": 68000,
                "fuel_type": Vehicle.FuelType.DIESEL,
                "gearbox": Vehicle.GearboxType.AUTOMATIC,
                "color": "Gris argent",
                "doors": 5,
                "seats": 5,
                "fiscal_power": 6,
                "power_hp": 115,
                "co2_emissions": 112,
                "consumption": 4.8,
                "crit_air": "Crit’Air 2",
                "warranty": "12 mois",
                "included_options": "GPS, Climatisation automatique, Aide au stationnement, Bluetooth, Régulateur adaptatif, Détecteur de pluie",
                "price_sale": 14800.00,
                "price_monthly": 119.00,
                "description": "Berline confortable et élégante, pensée pour les conducteurs recherchant sobriété et confort sur route. Elle dispose d’un bon niveau d’équipement avec GPS, climatisation automatique et aide au stationnement.",
                "offer_type": Vehicle.OfferType.LLD,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
            {
                "reference": "MM_PEU_001",
                "brand": "Peugeot",
                "model": "228",
                "trim": "Active",
                "category": "Citadine",
                "image": "img/catalog_cars/peugeot_bleue1.PNG",
                "year": 2021,
                "mileage": 39000,
                "fuel_type": Vehicle.FuelType.GASOLINE,
                "gearbox": Vehicle.GearboxType.MANUAL,
                "color": "Bleu foncé",
                "doors": 5,
                "seats": 5,
                "fiscal_power": 5,
                "power_hp": 100,
                "co2_emissions": 116,
                "consumption": 5.2,
                "crit_air": "Crit’Air 1",
                "warranty": "12 mois",
                "included_options": "Écran tactile, Bluetooth, Climatisation, Régulateur de vitesse, Limiteur de vitesse, Radar de recul",
                "price_sale": 13700.00,
                "price_monthly": 119.00,
                "description": "Citadine dynamique au design moderne, parfaite pour les jeunes conducteurs ou un usage urbain. Son moteur souple et son écran tactile rendent chaque trajet plus agréable.",
                "offer_type": Vehicle.OfferType.BOTH,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
            {
                "reference": "MM_PEU_002",
                "brand": "Peugeot",
                "model": "318",
                "trim": "Allure",
                "category": "Berline",
                "image": "img/catalog_cars/peugeot_grise1.PNG",
                "year": 2020,
                "mileage": 16500,
                "fuel_type": Vehicle.FuelType.HYBRID,
                "gearbox": Vehicle.GearboxType.MANUAL,
                "color": "Gris clair",
                "doors": 5,
                "seats": 5,
                "fiscal_power": 7,
                "power_hp": 136,
                "co2_emissions": 96,
                "consumption": 4.2,
                "crit_air": "Crit’Air 1",
                "warranty": "24 mois",
                "included_options": "GPS, Bluetooth, Caméra de recul, Climatisation automatique, Aide au maintien dans la voie, Régulateur de vitesse",
                "price_sale": 16500.00,
                "price_monthly": 149.00,
                "description": "Berline polyvalente appréciée pour son confort de conduite et sa faible consommation. Très bien équipée, elle convient aussi bien à la ville qu’aux longs trajets autoroutiers.",
                "offer_type": Vehicle.OfferType.LLD,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
            {
                "reference": "MM_PEU_003",
                "brand": "Peugeot",
                "model": "3009",
                "trim": "GT Line",
                "category": "SUV",
                "image": "img/catalog_cars/peugeot_souris1.PNG",
                "year": 2020,
                "mileage": 63000,
                "fuel_type": Vehicle.FuelType.DIESEL,
                "gearbox": Vehicle.GearboxType.AUTOMATIC,
                "color": "Gris souris",
                "doors": 5,
                "seats": 5,
                "fiscal_power": 8,
                "power_hp": 150,
                "co2_emissions": 128,
                "consumption": 5.5,
                "crit_air": "Crit’Air 2",
                "warranty": "12 mois",
                "included_options": "GPS, Caméra de recul, Radars avant et arrière, Toit panoramique, Bluetooth, Climatisation automatique",
                "price_sale": 21900.00,
                "price_monthly": 169.00,
                "description": "SUV élégant et haut de gamme, reconnu pour son confort, sa qualité intérieure et ses technologies embarquées. Une excellente option pour une famille recherchant un véhicule valorisant et pratique.",
                "offer_type": Vehicle.OfferType.BOTH,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
            {
                "reference": "MM_FOR_001",
                "brand": "Ford",
                "model": "Fiesto",
                "trim": "Trend",
                "category": "Citadine",
                "image": "img/catalog_cars/Ford_orange.png",
                "year": 2019,
                "mileage": 47000,
                "fuel_type": Vehicle.FuelType.GASOLINE,
                "gearbox": Vehicle.GearboxType.MANUAL,
                "color": "Orange",
                "doors": 5,
                "seats": 5,
                "fiscal_power": 5,
                "power_hp": 95,
                "co2_emissions": 118,
                "consumption": 5.4,
                "crit_air": "Crit’Air 1",
                "warranty": "12 mois",
                "included_options": "Bluetooth, Climatisation, Régulateur de vitesse, Aide au stationnement, Commandes au volant",
                "price_sale": 12600.00,
                "price_monthly": 119.00,
                "description": "Citadine nerveuse et agréable à conduire, très appréciée pour sa maniabilité et son confort. Un modèle compact parfait pour la ville avec un bon niveau d’équipement.",
                "offer_type": Vehicle.OfferType.SALE,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
            {
                "reference": "MM_FOR_002",
                "brand": "Ford",
                "model": "Focal",
                "trim": "Business",
                "category": "Berline",
                "image": "img/catalog_cars/Ford_blanche1.png",
                "year": 2020,
                "mileage": 54000,
                "fuel_type": Vehicle.FuelType.DIESEL,
                "gearbox": Vehicle.GearboxType.MANUAL,
                "color": "Blanc",
                "doors": 5,
                "seats": 5,
                "fiscal_power": 6,
                "power_hp": 120,
                "co2_emissions": 110,
                "consumption": 4.7,
                "crit_air": "Crit’Air 2",
                "warranty": "12 mois",
                "included_options": "GPS, Bluetooth, Climatisation automatique, Régulateur de vitesse, Radar de recul, Détecteur de pluie",
                "price_sale": 15900.00,
                "price_monthly": 129.00,
                "description": "Berline compacte équilibrée, idéale pour les trajets quotidiens comme pour la route. Elle offre une bonne tenue de route, une faible consommation et un intérieur confortable.",
                "offer_type": Vehicle.OfferType.LLD,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
            {
                "reference": "MM_FOR_003",
                "brand": "Ford",
                "model": "Kaga",
                "trim": "Titanium",
                "category": "SUV",
                "image": "img/catalog_cars/Ford_noire_break1.png",
                "year": 2021,
                "mileage": 66000,
                "fuel_type": Vehicle.FuelType.ELECTRIC,
                "gearbox": Vehicle.GearboxType.AUTOMATIC,
                "color": "Noir",
                "doors": 5,
                "seats": 5,
                "fiscal_power": 4,
                "power_hp": 170,
                "co2_emissions": 0,
                "consumption": 0,
                "crit_air": "Crit’Air 0",
                "warranty": "24 mois",
                "included_options": "GPS, Caméra de recul, Bluetooth, Climatisation automatique, Aide au stationnement, Régulateur adaptatif",
                "price_sale": 23400.00,
                "price_monthly": 159.00,
                "description": "SUV confortable et spacieux, pensé pour les familles et les conducteurs recherchant de la polyvalence. Il se distingue par son confort, son équipement complet et sa position de conduite agréable.",
                "offer_type": Vehicle.OfferType.BOTH,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
            {
                "reference": "MM_TOY_001",
                "brand": "Toyata",
                "model": "Yolo",
                "trim": "Dynamic",
                "category": "Citadine",
                "image": "img/catalog_cars/toyota_rouge1.png",
                "year": 2021,
                "mileage": 16800,
                "fuel_type": Vehicle.FuelType.GASOLINE,
                "gearbox": Vehicle.GearboxType.MANUAL,
                "color": "Rouge",
                "doors": 5,
                "seats": 5,
                "fiscal_power": 5,
                "power_hp": 100,
                "co2_emissions": 102,
                "consumption": 4.5,
                "crit_air": "Crit’Air 1",
                "warranty": "24 mois",
                "included_options": "Bluetooth, Climatisation automatique, Régulateur de vitesse, Caméra de recul, Écran tactile",
                "price_sale": 16800.00,
                "price_monthly": 129.00,
                "description": "Citadine hybride idéale pour la ville, réputée pour sa fiabilité et sa faible consommation. Très agréable en circulation urbaine, elle combine silence de fonctionnement et coût d’usage réduit.",
                "offer_type": Vehicle.OfferType.BOTH,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
            {
                "reference": "MM_TOY_002",
                "brand": "Toyata",
                "model": "Coriolis",
                "trim": "Business",
                "category": "Berline",
                "image": "img/catalog_cars/toyota_blanche1.png",
                "year": 2020,
                "mileage": 49000,
                "fuel_type": Vehicle.FuelType.HYBRID,
                "gearbox": Vehicle.GearboxType.AUTOMATIC,
                "color": "Blanc nacré",
                "doors": 5,
                "seats": 5,
                "fiscal_power": 6,
                "power_hp": 122,
                "co2_emissions": 88,
                "consumption": 3.9,
                "crit_air": "Crit’Air 1",
                "warranty": "24 mois",
                "included_options": "GPS, Bluetooth, Climatisation automatique, Caméra de recul, Aide au maintien dans la voie, Régulateur adaptatif",
                "price_sale": 21200.00,
                "price_monthly": 159.00,
                "description": "Berline moderne et efficiente, parfaite pour ceux qui recherchent confort, sobriété et fiabilité. Son moteur hybride assure une conduite fluide aussi bien en ville que sur route.",
                "offer_type": Vehicle.OfferType.SALE,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
            {
                "reference": "MM_TOY_003",
                "brand": "Toyata",
                "model": "C-MP",
                "trim": "Design",
                "category": "SUV",
                "image": "img/catalog_cars/toyota_bleue_break1.png",
                "year": 2021,
                "mileage": 43000,
                "fuel_type": Vehicle.FuelType.ELECTRIC,
                "gearbox": Vehicle.GearboxType.MANUAL,
                "color": "Bleu clair",
                "doors": 5,
                "seats": 5,
                "fiscal_power": 4,
                "power_hp": 145,
                "co2_emissions": 0,
                "consumption": 0,
                "crit_air": "Crit’Air 0",
                "warranty": "24 mois",
                "included_options": "GPS, Bluetooth, Caméra de recul, Climatisation automatique, Radar de recul, Régulateur de vitesse",
                "price_sale": 22700.00,
                "price_monthly": 179.00,
                "description": "SUV compact au design audacieux, très apprécié pour son confort et sa technologie hybride. Un modèle idéal pour se démarquer tout en maîtrisant sa consommation.",
                "offer_type": Vehicle.OfferType.LLD,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
            {
                "reference": "MM-SEED-001",
                "brand": "Renault",
                "model": "Clio",
                "trim": "Business",
                "category": "Citadine",
                "image": "img/catalog_cars/renault_bleue1.PNG",
                "year": 2022,
                "mileage": 18000,
                "fuel_type": Vehicle.FuelType.HYBRID,
                "gearbox": Vehicle.GearboxType.AUTOMATIC,
                "color": "Bleu métallisé",
                "doors": 5,
                "seats": 5,
                "fiscal_power": 5,
                "power_hp": 140,
                "co2_emissions": 96,
                "consumption": 4.3,
                "crit_air": "Crit’Air 1",
                "warranty": "24 mois",
                "included_options": "GPS, Bluetooth, Caméra de recul, Climatisation automatique, Régulateur de vitesse, Radar de recul",
                "price_sale": None,
                "price_monthly": 299.00,
                "description": "Véhicule de test pour seed",
                "offer_type": Vehicle.OfferType.LLD,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
            {
                "reference": "MM_FAM_001",
                "brand": "Renault",
                "model": "Scenic",
                "trim": "Business",
                "category": "Familiale",
                "image": "img/catalog_cars/renault_orange2.png",
                "year": 2021,
                "mileage": 52000,
                "fuel_type": Vehicle.FuelType.DIESEL,
                "gearbox": Vehicle.GearboxType.AUTOMATIC,
                "color": "Orange métallisé",
                "doors": 5,
                "seats": 5,
                "fiscal_power": 7,
                "power_hp": 150,
                "co2_emissions": 126,
                "consumption": 5.6,
                "crit_air": "Crit’Air 2",
                "warranty": "12 mois",
                "included_options": "GPS, Caméra de recul, Climatisation automatique, Bluetooth, Régulateur de vitesse, Radars avant et arrière",
                "price_sale": 18900.00,
                "price_monthly": 179.00,
                "description": "Monospace familial spacieux et confortable, idéal pour les trajets du quotidien comme pour les départs en vacances. Il offre un grand volume intérieur, une conduite souple et des équipements adaptés à la vie de famille.",
                "offer_type": Vehicle.OfferType.BOTH,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
            {
                "reference": "MM_FAM_002",
                "brand": "Peugeot",
                "model": "5008",
                "trim": "Allure",
                "category": "Familiale",
                "image": "img/catalog_cars/peugeot_grise2.png",
                "year": 2020,
                "mileage": 61000,
                "fuel_type": Vehicle.FuelType.DIESEL,
                "gearbox": Vehicle.GearboxType.AUTOMATIC,
                "color": "Gris métallisé",
                "doors": 5,
                "seats": 7,
                "fiscal_power": 8,
                "power_hp": 150,
                "co2_emissions": 132,
                "consumption": 5.9,
                "crit_air": "Crit’Air 2",
                "warranty": "12 mois",
                "included_options": "GPS, 7 places, Caméra de recul, Climatisation automatique, Bluetooth, Aide au stationnement, Régulateur de vitesse",
                "price_sale": 24900.00,
                "price_monthly": 219.00,
                "description": "SUV familial 7 places, pensé pour les familles recherchant de l’espace, du confort et de la modularité. Son habitacle généreux et son équipement complet en font un véhicule très polyvalent.",
                "offer_type": Vehicle.OfferType.BOTH,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
            {
                "reference": "MM_FAM_003",
                "brand": "Citroën",
                "model": "C4 Picasso",
                "trim": "Feel",
                "category": "Familiale",
                "image": "img/catalog_cars/citroen_bleue1.png",
                "year": 2019,
                "mileage": 74000,
                "fuel_type": Vehicle.FuelType.GASOLINE,
                "gearbox": Vehicle.GearboxType.MANUAL,
                "color": "Bleu",
                "doors": 5,
                "seats": 5,
                "fiscal_power": 6,
                "power_hp": 130,
                "co2_emissions": 115,
                "consumption": 5.6,
                "crit_air": "Crit’Air 1",
                "warranty": "12 mois",
                "included_options": "Climatisation automatique, GPS, Bluetooth, Régulateur de vitesse, Radar de recul, Aide au stationnement",
                "price_sale": 15900.00,
                "price_monthly": 149.00,
                "description": "Véhicule familial confortable et pratique, apprécié pour son habitabilité, sa visibilité et ses rangements. Une solution adaptée aux familles qui souhaitent un véhicule fiable et accessible.",
                "offer_type": Vehicle.OfferType.SALE,
                "availability_status": Vehicle.AvailabilityStatus.AVAILABLE,
            },
        ]

        seed_vehicle = None

        for vehicle_data in vehicles_data:
            reference = vehicle_data["reference"]
            vehicle_defaults = vehicle_data.copy()
            vehicle_defaults.pop("reference")

            vehicle, _ = Vehicle.objects.update_or_create(
                reference=reference,
                defaults=vehicle_defaults,
            )

            if vehicle.reference == "MM-SEED-001":
                seed_vehicle = vehicle

        if seed_vehicle is None:
            seed_vehicle = Vehicle.objects.get(reference="MM-SEED-001")

        dossier, _ = Dossier.objects.get_or_create(
            customer=user,
            vehicle=seed_vehicle,
            application_type=Dossier.ApplicationType.LLD,
            defaults={
                "status": Dossier.Status.SUBMITTED,
                "customer_note": "Dossier créé automatiquement par le seed",
                "internal_note": "Dossier de test",
            },
        )

        dossier.options.set(created_options)

        DossierStatusHistory.objects.get_or_create(
            dossier=dossier,
            old_status=Dossier.Status.DRAFT,
            new_status=Dossier.Status.SUBMITTED,
            defaults={
                "changed_by": user,
                "comment": "Création automatique via seed",
            },
        )

        self.stdout.write(self.style.SUCCESS("Seed terminé avec succès."))