# Generated by Django 6.0.4 on 2026-04-21 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default_in_lld', models.BooleanField(default=False)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('sale', 'Achat'), ('lld', 'Location')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('under_review', "En cours d'examen"), ('approved', 'Accepté'), ('rejected', 'Refusé')], default='draft', max_length=20)),
                ('customer_note', models.TextField(blank=True)),
                ('internal_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='catalog.vehicle')),
                ('options', models.ManyToManyField(blank=True, related_name='dossiers', to='dossiers.option')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', "Carte d'identité"), ('driver_license', 'Permis de conduire'), ('proof_of_address', 'Justificatif de domicile'), ('proof_of_income', 'Justificatif de revenus'), ('other', 'Autre')], max_length=30)),
                ('file', models.FileField(upload_to='documents/')),
                ('validation_status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Validé'), ('rejected', 'Refusé')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dossiers.dossier')),
            ],
        ),
        migrations.CreateModel(
            name='DossierStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('under_review', "En cours d'examen"), ('approved', 'Accepté'), ('rejected', 'Refusé')], max_length=20)),
                ('new_status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('under_review', "En cours d'examen"), ('approved', 'Accepté'), ('rejected', 'Refusé')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='dossiers.dossier')),
            ],
        ),
    ]
