# Generated by Django 6.0.4 on 2026-06-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='data_processing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossier',
            name='data_processing_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='has_current_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dossier',
            name='housing_status',
            field=models.CharField(blank=True, choices=[('tenant', 'Locataire'), ('owner', 'Propriétaire'), ('hosted', 'Hébergé')], max_length=20),
        ),
        migrations.AddField(
            model_name='dossier',
            name='monthly_credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('under_review', "En cours d'instruction"), ('approved', 'Accepté'), ('rejected', 'Refusé')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='dossierstatushistory',
            name='new_status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('under_review', "En cours d'instruction"), ('approved', 'Accepté'), ('rejected', 'Refusé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dossierstatushistory',
            name='old_status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis'), ('under_review', "En cours d'instruction"), ('approved', 'Accepté'), ('rejected', 'Refusé')], max_length=20),
        ),
    ]
