# Generated by Django 6.0.4 on 2026-06-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_dossier_data_processing_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('id_card', "Carte d'identité"), ('driver_license', 'Permis de conduire'), ('proof_of_address', 'Justificatif de domicile'), ('rent_receipt', 'Quittance de loyer'), ('proof_of_income', 'Justificatif de revenus'), ('other', 'Autre')], max_length=30),
        ),
    ]
