# Generated by Django 6.0.4 on 2026-06-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0003_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dossier',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
