# Generated by Django 6.0.4 on 2026-06-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_dossier_address_dossier_birth_date_dossier_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='housing_status',
            field=models.CharField(blank=True, choices=[('tenant', 'Locataire'), ('owner', 'Propriétaire')], max_length=20),
        ),
    ]
