# Generated by Django 6.0.4 on 2026-06-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_alter_dossier_housing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('id_card', "Carte d'identité"), ('driver_license', 'Permis de conduire'), ('proof_of_address', 'Justificatif de domicile'), ('proof_of_income', 'Justificatif de revenus'), ('tax_notice', "Avis d'imposition"), ('rent_receipt', 'Quittance de loyer'), ('other', 'Autre')], max_length=30),
        ),
    ]
