# Generated by Django 6.0.4 on 2026-06-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0006_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='lld_duration_months',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(24, '24 mois'), (36, '36 mois'), (48, '48 mois'), (60, '60 mois'), (72, '72 mois'), (84, '84 mois')], null=True),
        ),
    ]
