# Generated by Django 6.0.4 on 2026-06-09 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0007_dossier_lld_duration_months'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossierstatushistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='comment',
            new_name='rejection_reason',
        ),
        migrations.RenameField(
            model_name='dossierstatushistory',
            old_name='changed_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('id_card', "Carte d'identité"), ('driver_license', 'Permis de conduire'), ('proof_of_address', 'Justificatif de domicile'), ('proof_of_income', 'Justificatif de revenus'), ('tax_notice', "Avis d'imposition"), ('rent_receipt', 'Quittance de loyer'), ('other', 'Autre')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='dossiers/documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Refusé')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='dossierstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier_status_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
