# Generated by Django 6.0.4 on 2026-06-15 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0009_dossieradvisormessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossieradvisormessage',
            name='advisor_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dossieradvisormessage',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossieradvisormessage',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor_message_responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
