# Generated by Django 6.0.4 on 2026-04-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Essence'), ('diesel', 'Diesel'), ('hybrid', 'Hybride'), ('electric', 'Électrique')], max_length=20)),
                ('gearbox', models.CharField(choices=[('manual', 'Manuelle'), ('automatic', 'Automatique')], max_length=20)),
                ('price_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('offer_type', models.CharField(choices=[('sale', 'Achat'), ('lld', 'Location'), ('both', 'Achat et location')], max_length=20)),
                ('availability_status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('unavailable', 'Indisponible'), ('sold', 'Vendu'), ('rented', 'Loué')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
