# Generated by Django 6.0.4 on 2026-06-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
