# Generated by Django 6.0.4 on 2026-06-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='co2_emissions',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Émissions CO2'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='consumption',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Consommation moyenne'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='crit_air',
            field=models.CharField(blank=True, max_length=20, verbose_name='Crit’Air'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='doors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nombre de portes'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fiscal_power',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Puissance fiscale'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='included_options',
            field=models.TextField(blank=True, verbose_name='Options incluses'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='power_hp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Puissance DIN'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seats',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nombre de places'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Garantie'),
        ),
    ]
